module.exports =
  ActionSources:
    SERVER_ACTION: 'SERVER_ACTION'
    VIEW_ACTION:   'VIEW_ACTION'

  ActionTypes:
    ADD_TASK:     'ADD_TASK'
    REMOVE_TASK:  'REMOVE_TASK'
    TOGGLE_TASK:  'TOGGLE_TASK'
    CLEAR_TASKS:  'CLEAR_TASKS'
